name: Core
on: push
jobs:
  testing:
    name: Testing
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: Checkout repository
        uses: actions/checkout@v4
      - id: setup
        name: Setup Rust
        uses: docker://rust:1.74.0
      - id: test
        name: Run test
        run: |
          cargo update
          cargo test -p sheave-core
